/* Copyright (C) 2022 Alif Semiconductor - All Rights Reserved.
 * Use, distribution and modification of this code is permitted under the
 * terms stated in the Alif Semiconductor Software License Agreement
 *
 * You should have received a copy of the Alif Semiconductor Software
 * License Agreement with this file. If not, please write to:
 * contact@alifsemi.com, or visit: https://alifsemi.com/license
 *
 */

/******************************************************************************
 * @file     board_AppKit_Alpha1.c
 * @brief    BOARD API implementation for Alif AI/ML Application Kit (Rev. A)
 ******************************************************************************/

#include "board.h"

#if defined(BOARD_IS_ALIF_APPKIT_ALPHA1_VARIANT)
#include "Driver_GPIO.h"
#include "Driver_PINMUX_AND_PINPAD.h"

#include "drv_i2c_bitbang.h"

extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_LED1_GPIO_PORT);
extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_LED2_GPIO_PORT);

void BOARD_Pinmux_Init()
{
	extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_LCD_RESET_GPIO_PORT);
	extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_LCD_BACKLIGHT_GPIO_PORT);
	extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_TOUCH_RESET_GPIO_PORT);
	extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_TOUCH_INT_GPIO_PORT);
	extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_CAMERA_RESET_GPIO_PORT);
	extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_CAMERA_POWER_GPIO_PORT);

	ARM_DRIVER_GPIO *BOARD_LED1_GPIOdrv = &ARM_Driver_GPIO_(BOARD_LED1_GPIO_PORT);
	ARM_DRIVER_GPIO *BOARD_LED2_GPIOdrv = &ARM_Driver_GPIO_(BOARD_LED2_GPIO_PORT);
	ARM_DRIVER_GPIO *BOARD_LCD_RESET_GPIOdrv = &ARM_Driver_GPIO_(BOARD_LCD_RESET_GPIO_PORT);
	ARM_DRIVER_GPIO *BOARD_LCD_BACKLIGHT_GPIOdrv = &ARM_Driver_GPIO_(BOARD_LCD_BACKLIGHT_GPIO_PORT);
	ARM_DRIVER_GPIO *BOARD_TOUCH_RESET_GPIOdrv = &ARM_Driver_GPIO_(BOARD_TOUCH_RESET_GPIO_PORT);
	ARM_DRIVER_GPIO *BOARD_TOUCH_INT_GPIOdrv = &ARM_Driver_GPIO_(BOARD_TOUCH_INT_GPIO_PORT);
	ARM_DRIVER_GPIO *BOARD_CAMERA_RESET_GPIOdrv = &ARM_Driver_GPIO_(BOARD_CAMERA_RESET_GPIO_PORT);
	ARM_DRIVER_GPIO *BOARD_CAMERA_POWER_GPIOdrv = &ARM_Driver_GPIO_(BOARD_CAMERA_POWER_GPIO_PORT);

	uint32_t config_pin_input =
			PAD_FUNCTION_READ_ENABLE |
			PAD_FUNCTION_SCHMITT_TRIGGER_ENABLE;

	uint32_t config_pin_inout_nopull =
			PAD_FUNCTION_READ_ENABLE;

	/* GPIO interfaces - initial GPIO state is lowest power */

	*((uint32_t *)0x71006010) = 0;
	*((uint32_t *)0x71006014) = 0;
	*((uint32_t *)0x71006018) = 0;
	*((uint32_t *)0x7100601C) = 0x11110011;	/* PINMUX for JTAG and SE-UART on OUTPUT_A */
	*((uint32_t *)0x71006020) = 0;
	*((uint32_t *)0x71006024) = 0;
	*((uint32_t *)0x71006028) = 0;
	*((uint32_t *)0x7100602C) = 0;
	*((uint32_t *)0x71006030) = 0;
	*((uint32_t *)0x71006034) = 0;
	*((uint32_t *)0x71006038) = 0;

	BOARD_LED1_GPIOdrv->SetValue(BOARD_LED1_PIN_NO, GPIO_PIN_OUTPUT_STATE_LOW);
	BOARD_LED1_GPIOdrv->SetDirection(BOARD_LED1_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
	PINMUX_Config(BOARD_LED1_GPIO_PORT, BOARD_LED1_PIN_NO, PINMUX_ALTERNATE_FUNCTION_0);
	PINPAD_Config(BOARD_LED1_GPIO_PORT, BOARD_LED1_PIN_NO, config_pin_inout_nopull);

	BOARD_LED2_GPIOdrv->SetValue(BOARD_LED2_PIN_NO, GPIO_PIN_OUTPUT_STATE_LOW);
	BOARD_LED2_GPIOdrv->SetDirection(BOARD_LED2_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
	PINMUX_Config(BOARD_LED2_GPIO_PORT, BOARD_LED2_PIN_NO, PINMUX_ALTERNATE_FUNCTION_0);
	PINPAD_Config(BOARD_LED2_GPIO_PORT, BOARD_LED2_PIN_NO, config_pin_inout_nopull);

	BOARD_LCD_RESET_GPIOdrv->SetValue(BOARD_LCD_RESET_PIN_NO, GPIO_PIN_OUTPUT_STATE_LOW);
	BOARD_LCD_RESET_GPIOdrv->SetDirection(BOARD_LCD_RESET_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
	PINMUX_Config(BOARD_LCD_RESET_GPIO_PORT, BOARD_LCD_RESET_PIN_NO, PINMUX_ALTERNATE_FUNCTION_0);
	PINPAD_Config(BOARD_LCD_RESET_GPIO_PORT, BOARD_LCD_RESET_PIN_NO, config_pin_inout_nopull);

	BOARD_LCD_BACKLIGHT_GPIOdrv->SetValue(BOARD_LCD_BACKLIGHT_PIN_NO, GPIO_PIN_OUTPUT_STATE_LOW);
	BOARD_LCD_BACKLIGHT_GPIOdrv->SetDirection(BOARD_LCD_BACKLIGHT_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
	PINMUX_Config(BOARD_LCD_BACKLIGHT_GPIO_PORT, BOARD_LCD_BACKLIGHT_PIN_NO, PINMUX_ALTERNATE_FUNCTION_0);
	PINPAD_Config(BOARD_LCD_BACKLIGHT_GPIO_PORT, BOARD_LCD_BACKLIGHT_PIN_NO, config_pin_inout_nopull);

	BOARD_TOUCH_RESET_GPIOdrv->SetValue(BOARD_TOUCH_RESET_PIN_NO, GPIO_PIN_OUTPUT_STATE_LOW);
	BOARD_TOUCH_RESET_GPIOdrv->SetDirection(BOARD_TOUCH_RESET_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
	PINMUX_Config(BOARD_TOUCH_RESET_GPIO_PORT, BOARD_TOUCH_RESET_PIN_NO, PINMUX_ALTERNATE_FUNCTION_0);
	PINPAD_Config(BOARD_TOUCH_RESET_GPIO_PORT, BOARD_TOUCH_RESET_PIN_NO, config_pin_inout_nopull);

	BOARD_TOUCH_INT_GPIOdrv->SetValue(BOARD_TOUCH_INT_PIN_NO, GPIO_PIN_OUTPUT_STATE_LOW);
	BOARD_TOUCH_INT_GPIOdrv->SetDirection(BOARD_TOUCH_INT_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
	PINMUX_Config(BOARD_TOUCH_INT_GPIO_PORT, BOARD_TOUCH_INT_PIN_NO, PINMUX_ALTERNATE_FUNCTION_0);
	PINPAD_Config(BOARD_TOUCH_INT_GPIO_PORT, BOARD_TOUCH_INT_PIN_NO, config_pin_input);

	BOARD_CAMERA_RESET_GPIOdrv->SetValue(BOARD_CAMERA_RESET_PIN_NO, GPIO_PIN_OUTPUT_STATE_LOW);
	BOARD_CAMERA_RESET_GPIOdrv->SetDirection(BOARD_CAMERA_RESET_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
	PINMUX_Config(BOARD_CAMERA_RESET_GPIO_PORT, BOARD_CAMERA_RESET_PIN_NO, PINMUX_ALTERNATE_FUNCTION_0);
	PINPAD_Config(BOARD_CAMERA_RESET_GPIO_PORT, BOARD_CAMERA_RESET_PIN_NO, config_pin_inout_nopull);

	BOARD_CAMERA_POWER_GPIOdrv->SetValue(BOARD_CAMERA_POWER_PIN_NO, GPIO_PIN_OUTPUT_STATE_LOW);
	BOARD_CAMERA_POWER_GPIOdrv->SetDirection(BOARD_CAMERA_POWER_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
	PINMUX_Config(BOARD_CAMERA_POWER_GPIO_PORT, BOARD_CAMERA_POWER_PIN_NO, PINMUX_ALTERNATE_FUNCTION_0);
	PINPAD_Config(BOARD_CAMERA_POWER_GPIO_PORT, BOARD_CAMERA_POWER_PIN_NO, config_pin_inout_nopull);

	/* CAMERA clock output */
	PINMUX_Config(PORT_NUMBER_3, PIN_NUMBER_15, PINMUX_ALTERNATE_FUNCTION_7);

	i2c_init();
}

void BOARD_Power_Init()
{
	/* Configure any board level power supplies */

	/* BOARD_LCD_BACKLIGHT_GPIO_PORT */
	extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_LCD_BACKLIGHT_GPIO_PORT);
	ARM_DRIVER_GPIO *LCD_BACKLIGHT_POWER_GPIO = &ARM_Driver_GPIO_(BOARD_LCD_BACKLIGHT_GPIO_PORT);

	LCD_BACKLIGHT_POWER_GPIO->Initialize(BOARD_LCD_BACKLIGHT_PIN_NO, NULL);
	LCD_BACKLIGHT_POWER_GPIO->PowerControl(BOARD_LCD_BACKLIGHT_PIN_NO,  ARM_POWER_FULL);
	LCD_BACKLIGHT_POWER_GPIO->SetValue(BOARD_LCD_BACKLIGHT_PIN_NO, GPIO_PIN_OUTPUT_STATE_HIGH);
	LCD_BACKLIGHT_POWER_GPIO->SetDirection(BOARD_LCD_BACKLIGHT_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);

	/* BOARD_CAMERA_POWER_GPIO_PORT */
	extern ARM_DRIVER_GPIO ARM_Driver_GPIO_(BOARD_CAMERA_POWER_GPIO_PORT);
	ARM_DRIVER_GPIO *CAMERA_POWER_GPIO = &ARM_Driver_GPIO_(BOARD_CAMERA_POWER_GPIO_PORT);

	CAMERA_POWER_GPIO->Initialize(BOARD_CAMERA_POWER_PIN_NO, NULL);
	CAMERA_POWER_GPIO->PowerControl(BOARD_CAMERA_POWER_PIN_NO,  ARM_POWER_FULL);
	CAMERA_POWER_GPIO->SetValue(BOARD_CAMERA_POWER_PIN_NO, GPIO_PIN_OUTPUT_STATE_HIGH);
	CAMERA_POWER_GPIO->SetDirection(BOARD_CAMERA_POWER_PIN_NO, GPIO_PIN_DIRECTION_OUTPUT);
}

void BOARD_Clock_Init()
{
	/* Configure any SoC clock muxes and dividers
	 * if not already covered in driver code
	 */
}

void BOARD_BUTTON1_Init(BOARD_Callback_t user_cb) { /* not implemented */ }
void BOARD_BUTTON2_Init(BOARD_Callback_t user_cb) { /* not implemented */ }

void BOARD_BUTTON1_Control(BOARD_BUTTON_CONTROL control) { /* not implemented */ }
void BOARD_BUTTON2_Control(BOARD_BUTTON_CONTROL control) { /* not implemented */ }

void BOARD_BUTTON1_GetState(BOARD_BUTTON_STATE *state)
{
    /* not implemented */
	*state = BOARD_BUTTON_STATE_LOW;
}

void BOARD_BUTTON2_GetState(BOARD_BUTTON_STATE *state)
{
    /* not implemented */
	*state = BOARD_BUTTON_STATE_LOW;
}

void BOARD_LED1_Control(BOARD_LED_STATE state){
	ARM_DRIVER_GPIO *BOARD_LED1_GPIOdrv = &ARM_Driver_GPIO_(BOARD_LED1_GPIO_PORT);
	BOARD_LED1_GPIOdrv->SetValue(BOARD_LED1_PIN_NO, state);
}

void BOARD_LED2_Control(BOARD_LED_STATE state)
{
	ARM_DRIVER_GPIO *BOARD_LED2_GPIOdrv = &ARM_Driver_GPIO_(BOARD_LED2_GPIO_PORT);
	BOARD_LED2_GPIOdrv->SetValue(BOARD_LED2_PIN_NO, state);
}

#endif
